version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
    volumes:
      [./pgdata:/var/lib/postgresql/data]
    ports:
      ["5432:5432"]